[package]
name = "dc-installer"
description = "Devil Connection Korean patch installer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "dc-patcher"
path = "src/main.rs"

[dependencies]
dc-asar = { path = "../dc-asar" }

anyhow.workspace = true
clap.workspace = true
fs4.workspace = true
hex.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
dc-asar = { path = "../dc-asar" }
tempfile.workspace = true
